### PR TITLE
Form.json with all questions

### PR DESCRIPTION
**Pull request by hodgka**
Working form.json, not all questions are formatted quite properly, yet.

### CODE REVIEW

**Comment by hodgka** [comment]
Two commits with different versions of the form. First commit has version that should work regardless. Second commit has changes dependent on changes to slider.

Both commits need to be tested.

**Comment by seveibar** [comment]
The "type" should have remained choice. In form.json (unfortunately) slider is equivalent to "numeric" and doesn't correspond to the ui element- this is kind of a bug in and of itself

**Review by seveibar — CHANGES_REQUESTED** [review]
"distance-frome-home"

**Comment by seveibar** [comment]
```javascript
{
            "id": "distance-frome-home",
            "question": "How far away from home was the college you attended?",
            "type": "choice",
            "range": ["In the same county", "In the same State", "On the same coast", "In the same country"]
        }
```

should use "answers":[...]

**Pull request closed without merging**
