### PR TITLE
Form.json updated

### PR DESCRIPTION
**Pull request by hodgka**
Form.json should work now.  Still need to add conditional branching and deal with SAT 2 scores.

### CODE REVIEW

**Comment by zlalvani** [comment]
What do you mean by conditional branching?

**Comment by hodgka** [comment]
The conditions for choosing which page to go to. It's at the bottom of each "page" object. Right now all the conditions are just set to true.

**Comment by hodgka** [comment]
The thing joey inplemented

**Comment by seveibar** [comment]
is the condition a required field of the yaml? it doesn't just default to true?

**Comment by seveibar** [comment]
@hodgka you have a conflict

**Comment by hodgka** [comment]
I don't think anything was ever implemented for yaml.

**Comment by hodgka** [comment]
Rebased branch, merge conflicts should be taken care of.

**Review by seveibar — APPROVED** [review]

**Pull request merged**
